// <auto-generated />
using System;
using EjercicioOrdenador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EjercicioOrdenador.Migrations
{
    [DbContext(typeof(TiendaOrdenadorContext))]
    [Migration("20230821085542_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EjercicioOrdenador.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calor")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Megas")
                        .HasColumnType("bigint");

                    b.Property<int?>("OrdenadorId")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenadorId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calor = 10,
                            Cores = 9,
                            Description = "Procesador Intel i7",
                            Megas = 0L,
                            OrdenadorId = 1,
                            Precio = 134.0,
                            Serie = "789-XCS",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            Calor = 12,
                            Cores = 10,
                            Description = "Procesador Intel i7",
                            Megas = 0L,
                            Precio = 138.0,
                            Serie = "789-XCD",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Calor = 22,
                            Cores = 11,
                            Description = "Procesador Intel i7",
                            Megas = 0L,
                            Precio = 138.0,
                            Serie = "789-XCT",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            Calor = 10,
                            Cores = 0,
                            Description = "Banco de Memoria SDRAM",
                            Megas = 512L,
                            OrdenadorId = 1,
                            Precio = 100.0,
                            Serie = "879FH",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Calor = 15,
                            Cores = 0,
                            Description = "Banco de Memoria SDRAM",
                            Megas = 1024L,
                            Precio = 125.0,
                            Serie = "879FH-L",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 6,
                            Calor = 24,
                            Cores = 0,
                            Description = "Banco de Memoria SDRAM",
                            Megas = 2048L,
                            OrdenadorId = 2,
                            Precio = 150.0,
                            Serie = "879FH-T",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 7,
                            Calor = 10,
                            Cores = 0,
                            Description = "DiscoDuro SanDisk",
                            Megas = 512000L,
                            OrdenadorId = 1,
                            Precio = 50.0,
                            Serie = "789-XX",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 8,
                            Calor = 29,
                            Cores = 0,
                            Description = "DiscoDuro SanDisk",
                            Megas = 1024000L,
                            Precio = 90.0,
                            Serie = "789-XX-2",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 9,
                            Calor = 39,
                            Cores = 0,
                            Description = "DiscoDuro SanDisk",
                            Megas = 2048000L,
                            OrdenadorId = 2,
                            Precio = 128.0,
                            Serie = "789-XX-3",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 10,
                            Calor = 30,
                            Cores = 10,
                            Description = "Procesador Ryzen AMD",
                            Megas = 0L,
                            Precio = 78.0,
                            Serie = "797-X",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 11,
                            Calor = 30,
                            Cores = 29,
                            Description = "Procesador Ryzen AMD",
                            Megas = 0L,
                            Precio = 178.0,
                            Serie = "797-X2",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 12,
                            Calor = 60,
                            Cores = 34,
                            Description = "Procesador Ryzen AMD",
                            Megas = 0L,
                            OrdenadorId = 2,
                            Precio = 278.0,
                            Serie = "797-X3",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 13,
                            Calor = 35,
                            Cores = 0,
                            Description = "Disco Mecánico Patatin",
                            Megas = 250L,
                            Precio = 37.0,
                            Serie = "788-fg",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 14,
                            Calor = 35,
                            Cores = 0,
                            Description = "Disco Mecánico Patatin",
                            Megas = 250L,
                            Precio = 67.0,
                            Serie = "788-fg-2",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 15,
                            Calor = 35,
                            Cores = 0,
                            Description = "Disco Mecánico Patatin",
                            Megas = 250L,
                            Precio = 97.0,
                            Serie = "788-fg-3",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 16,
                            Calor = 10,
                            Cores = 0,
                            Description = "Disco Externo Sam",
                            Megas = 9216000L,
                            Precio = 134.0,
                            Serie = "1789-XCS",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 17,
                            Calor = 12,
                            Cores = 0,
                            Description = "Disco Externo Sam",
                            Megas = 10240000L,
                            Precio = 138.0,
                            Serie = "1789-XCD",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 18,
                            Calor = 22,
                            Cores = 0,
                            Description = "Disco Externo Sam",
                            Megas = 11264000L,
                            Precio = 140.0,
                            Serie = "1789-XCT",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("EjercicioOrdenador.Models.Ordenador", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Ordenadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ordenador Maria"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ordenador Andres"
                        });
                });

            modelBuilder.Entity("EjercicioOrdenador.Models.Componente", b =>
                {
                    b.HasOne("EjercicioOrdenador.Models.Ordenador", "MiOrdenador")
                        .WithMany("Componentes")
                        .HasForeignKey("OrdenadorId");

                    b.Navigation("MiOrdenador");
                });

            modelBuilder.Entity("EjercicioOrdenador.Models.Ordenador", b =>
                {
                    b.Navigation("Componentes");
                });
#pragma warning restore 612, 618
        }
    }
}
